version: '3'
services:
  ms-sql:
    image: mcr.microsoft.com/mssql/server
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Strong.Pwd-123"
    ports:
      - "1433:1433"
  app:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - ms-sql